# Generated by Django 6.1.1 on 2026-10-02 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagerecord',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
