# Generated by Django 6.1.1 on 2026-10-03 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0002_alter_imagerecord_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagerecord',
            name='processed_image',
            field=models.ImageField(blank=True, null=True, upload_to='processed/'),
        ),
    ]
