# Generated by Django 6.1.1 on 2026-10-03 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0003_imagerecord_processed_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagerecord',
            name='enhanced_image',
            field=models.ImageField(blank=True, null=True, upload_to='enhanced/'),
        ),
    ]
