# Generated by Django 6.1.1 on 2026-10-03 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0004_imagerecord_enhanced_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagerecord',
            name='leaf_mask',
            field=models.ImageField(blank=True, null=True, upload_to='masks/'),
        ),
    ]
