# Generated by Django 6.1.1 on 2026-10-06 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0005_imagerecord_leaf_mask'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagerecord',
            name='edge_image',
            field=models.ImageField(blank=True, null=True, upload_to='edges/'),
        ),
    ]
