# Generated by Django 6.1.1 on 2026-10-06 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0006_imagerecord_edge_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagerecord',
            name='disease_mask',
            field=models.ImageField(blank=True, null=True, upload_to='disease_masks/'),
        ),
    ]
