# Generated by Django 6.1.1 on 2026-10-06 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0007_imagerecord_disease_mask'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagerecord',
            name='affected_area_percentage',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='imagerecord',
            name='disease_pixel_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='imagerecord',
            name='leaf_pixel_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
