# Generated by Django 6.1.1 on 2026-10-06 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0008_imagerecord_affected_area_percentage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagerecord',
            name='ai_confidence',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='imagerecord',
            name='ai_disease',
            field=models.CharField(default='Unknown', max_length=200),
        ),
        migrations.AddField(
            model_name='imagerecord',
            name='ai_plant',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='imagerecord',
            name='ai_possible_causes',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='imagerecord',
            name='ai_recommendation',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='imagerecord',
            name='ai_severity',
            field=models.CharField(default='Unknown', max_length=50),
        ),
        migrations.AddField(
            model_name='imagerecord',
            name='ai_symptoms',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
